version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: "task-management"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_management
    ports:
      - "5432:5432"